import { Album } from "@/types/album";

export const popularAlbums: Album[] = [
  {
    id: 1,
    title: "Hurry Up Tomorrow",
    artist: "The Weeknd",
    cover: "/p1.jpg",
    rating: "4.5", // Updated to be between 0 and 5
    avgRating: "4.5",
    yourRating: "0",
    albumTracks: "12",
    releaseDate: "2021-05-14",
    duration: 52,
    label: "XO, Republic Records",
    explicit: true,
    genres: ["R&B", "Pop", "Alternative R&B"],
    trackCount: "12",
    tracks: [
      { title: "Intro", duration: "1:45", rating: "4.2" },
      { title: "Midnight Love", duration: "3:32", rating: "4.7" },
      { title: "Lost in Dreams", duration: "4:12", rating: "4.5" },
      { title: "Heartbreak Anthem", duration: "3:55", rating: "4.3" },
      { title: "Echoes", duration: "4:08", rating: "3.9" },
    ],
  },
  {
    id: 2,
    title: "HIT ME HARD AND SOFT",
    artist: "Billie Eilish",
    cover: "/p2.jpg",
    rating: "4.7", // Updated to be between 0 and 5
    avgRating: "4.7",
    yourRating: "0",
    albumTracks: "10",
    releaseDate: "2024-05-17",
    duration: 43,
    label: "Darkroom, Interscope Records",
    explicit: true,
    genres: ["Alternative", "Indie Pop"],
    trackCount: "10",
    tracks: [
      { title: "Soft Start", duration: "2:11", rating: "4.1" },
      { title: "Harder Now", duration: "3:22", rating: "4.6" },
      { title: "Echo Chamber", duration: "4:05", rating: "4.8" },
      { title: "Lost Myself", duration: "3:50", rating: "4.4" },
      { title: "Home", duration: "4:14", rating: "4.7" },
    ],
  },
  {
    id: 3,
    title: "Alligator Bites Never Hurt",
    artist: "Doechii",
    cover: "/p4.jpg",
    rating: "4.3", // Updated to be between 0 and 5
    avgRating: "4.3",
    yourRating: "0",
    albumTracks: "14",
    releaseDate: "2024-07-10",
    duration: 38,
    label: "Top Dawg Entertainment",
    explicit: true,
    genres: ["Hip-Hop", "R&B", "Experimental"],
    trackCount: "14",
    tracks: [
      { title: "Intro", duration: "1:55", rating: "4.0" },
      { title: "Lights Out", duration: "3:48", rating: "4.6" },
      { title: "Reckless", duration: "4:01", rating: "4.3" },
      { title: "Desert Storm", duration: "3:33", rating: "3.8" },
      { title: "Elevate", duration: "4:21", rating: "4.5" },
    ],
  },
  {
    id: 4,
    title: "BRAT",
    artist: "Charli XCX",
    cover: "/p5.jpg",
    rating: "4.6", // Updated to be between 0 and 5
    avgRating: "4.6",
    yourRating: "0",
    albumTracks: "13",
    releaseDate: "2024-06-07",
    duration: 41,
    label: "Atlantic Records",
    explicit: true,
    genres: ["Hyperpop", "Electropop", "Dance"],
    trackCount: "13",
    tracks: [
      { title: "Digital Dreams", duration: "2:57", rating: "4.7" },
      { title: "Hyperlove", duration: "3:12", rating: "4.5" },
      { title: "Fast Lane", duration: "4:00", rating: "4.3" },
      { title: "Neon Lights", duration: "3:29", rating: "4.0" },
      { title: "Electric Heart", duration: "3:55", rating: "4.2" },
    ],
  },
  {
    id: 5,
    title: "IGOR",
    artist: "Tyler, The Creator",
    cover: "/p6.jpg",
    rating: "4.8", // Updated to be between 0 and 5
    avgRating: "4.8",
    yourRating: "0",
    albumTracks: "12",
    releaseDate: "2019-05-17",
    duration: 52,
    label: "Columbia Records",
    explicit: true,
    genres: ["Hip-Hop", "Neo-Soul", "Alternative"],
    trackCount: "12",
    tracks: [
      { title: "IGOR'S THEME", duration: "3:20", rating: "4.9" },
      { title: "EARFQUAKE", duration: "3:10", rating: "5.0" },
      { title: "I THINK", duration: "3:32", rating: "4.7" },
      { title: "EXACTLY WHAT YOU RUN FROM", duration: "0:14", rating: "3.5" },
      { title: "RUNNING OUT OF TIME", duration: "2:57", rating: "4.3" },
    ],
  },
  {
    id: 6,
    title: "Blonde",
    artist: "Frank Ocean",
    cover: "/p6.jpg",
    rating: "4.9", // Updated to be between 0 and 5
    avgRating: "4.9",
    yourRating: "0",
    albumTracks: "17",
    releaseDate: "2016-08-20",
    duration: 60,
    label: "Boys Don't Cry",
    explicit: false,
    genres: ["R&B", "Alternative", "Experimental"],
    trackCount: "17",
    tracks: [
      { title: "Nikes", duration: "5:14", rating: "5.0" },
      { title: "Ivy", duration: "4:09", rating: "4.9" },
      { title: "Pink + White", duration: "3:04", rating: "4.8" },
      { title: "Solo", duration: "4:17", rating: "4.7" },
      { title: "Skyline To", duration: "3:06", rating: "4.6" },
    ],
  },
  {
    id: 7,
    title: "CHROMAKOPIA",
    artist: "Tyler, The Creator",
    cover: "/p1.jpg",
    rating: "4.4", // Updated to be between 0 and 5
    avgRating: "4.4",
    yourRating: "0",
    albumTracks: "11",
    releaseDate: "2025-02-10",
    duration: 48,
    label: "Columbia Records",
    explicit: true,
    genres: ["Hip-Hop", "Alternative", "Experimental"],
    trackCount: "11",
    tracks: [
      { title: "Sunset Drive", duration: "3:33", rating: "4.5" },
      { title: "No Signal", duration: "4:12", rating: "4.3" },
      { title: "Glass House", duration: "3:47", rating: "4.2" },
      { title: "Digital Veins", duration: "4:05", rating: "4.4" },
      { title: "Final Frontier", duration: "3:59", rating: "4.6" },
    ],
  },
];
